image_size: 128
image_channels: 3
image_max_value: 255
image_min_value: 0
num_classes: 2
num_diffusion_timesteps: 1000
max_beta: 0.999
s: 0.008
lambda_variational: 0.001
model_in_ch: 3
model_out_ch: 6
lr: 0.0001
grad_clip: 1.0
data_dir: "/home/orkhan/sat25k"
train_batch_size: 8
sample_batch_size: 8
artifact_dir: "/tmp/syn10"
checkpoint_freq: 100

