image_channels: 3
image_max_value: 255
image_min_value: 0
num_classes: 2
s: 0.008
max_beta: 0.999
lambda_variational: 0.001
num_diffusion_timesteps: 1000
p_uncond: 0.2
lr: 0.00002
grad_clip: 1.0
weight_decay: 0.05
norm_channels: 32
model_input_channels: 3
model_output_channels: 6
ema_decay: 0.9999
guidance: 1.5
attn_resolutions: [32, 16, 8]
num_resnet_blocks: 2
t_embed_mult: 4.0
y_embed_mult: 1.0
lr_scheduler_t_mult: 1
train_batch_size: 8
sample_batch_size: 8
ema_delay: 10000
image_size: 128
dropout: 0.0
num_epochs: 401
channel_mult: [1, 1, 2, 3, 4]
model_channels: 128
head_channels: 64
lr_scheduler_t_0: 401
checkpoint_freq: 50000
tensorboard_freq: 2500
eval_freq: 50000