image_size: 128
image_channels: 3
image_max_value: 255
image_min_value: 0
num_classes: 2
num_epochs: 10000
num_diffusion_timesteps: 1000
max_beta: 0.999
s: 0.008
lambda_variational: 0.001
norm_channels: 32
model_input_channels: 3
model_output_channels: 6
model_channels: 128
channel_mult: [1, 2, 4]
num_resnet_blocks: 2
attn_resolutions: [32, ]
head_channels: 32
t_embed_mult: 4
y_embed_mult: 0.5
dropout: 0.0
lr: 0.0001
lr_scheduler_t_0: 10
lr_scheduler_t_mult: 2
grad_clip: 1.0
train_batch_size: 4
sample_batch_size: 4
checkpoint_freq: 100
tensorboard_freq: 100
guidance: 1.5
p_uncond: 0.2
ema_decay: 0.9999
ema_delay: 100000
weight_decay: 0.05
