image_size: 128
image_channels: 3
image_max_value: 255
image_min_value: 0
num_classes: 2
num_epochs: 10000
num_diffusion_timesteps: 1000
max_beta: 0.999
s: 0.008
lambda_variational: 0.001
model_in_ch: 3
model_out_ch: 6
lr: 0.0001
grad_clip: 1.0
train_batch_size: 4
sample_batch_size: 4
checkpoint_freq: 100
tensorboard_freq: 100
guidance: 1.5
